name: CI

on:
  push:
    branches: master
  workflow_dispatch: 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Cloning repo
        uses: actions/checkout@v3
        
      - name: Newman Action
        uses: matt-ball/newman-action@v1.0.4

      - name: Performing tests
        run: newman run Frankenstein_collection.postman_collection.json
