name: CI

on:
  push:
    branches: master
  workflow_dispatch: 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Cloning repo
        uses: actions/checkout@v3
        
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: Frankenstein_collection.postman_collection.json
          environment: postman_environment.json

      - name: Performing tests
        run: newman run Frankenstein_collection.postman_collection.json
