name: CI

on:
  push:
    branches: master
  workflow_dispatch: 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Cloning repo
        uses: actions/checkout@v3
        
# matt-ball/newman-action@v1.0.4
      - name: Trying to use cd
        run: cd
