name: CI

on:
  push:
    branches: master
  workflow_dispatch: 

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Cloning repo
      - uses: actions/checkout@v3

      - name: Setting up Newman
      - uses: matt-ball/newman-action@v1.0.4

      - name: Performing tests
      - run: cd
